#rpc can be local OR remote
rpc = 'http://localhost:8899'

#target is the prometheus server - may be local or not
target = '0.0.0.0:9179'
vote_account_whitelist = [
    'a',
    'b',
    'c'
]
staking_account_whitelist = [
    'aa',
    'bb',
    'cc'
]

#API key and token, not your login, update field names

[maxmind]
username = "12345"
password = "replace_me"
